Q1. Most selling Product
Considering the given Sales data, which of these is the most selling Product based irrespective of their Price?

Dataset: https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link

Choose the correct answer from below:

WORLD WAR 2 GLIDERS ASSTD DESIGNS

BLACK AND WHITE PAISLEY FLOWER MUG

PACK OF 60 PINK PAISLEY CAKE CASES

WHITE HANGING HEART T-LIGHT HOLDER

In [2]:
import pandas as pd
file_id = '1UViHcT4lKDsTfc97gBqIvds25uHe4b5e'
direct_download_url = f'https://drive.google.com/uc?id={file_id}'

# Read the CSV directly into a DataFrame
df = pd.read_csv(direct_download_url)
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [13]:
df.groupby(by='StockCode')['Quantity'].sum().sort_values(ascending=False)

StockCode
84077     108545
85123A     96066
85099B     95739
21212      95450
84879      80705
           ...
10120      -8350
23003      -8516
23005     -14418
22126     -16400
20852     -18800
Name: Quantity, Length: 5305, dtype: int64

In [14]:
df[df['StockCode']=='84077']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1309,489561,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2009-12-01 12:57:00,0.21,14654.0,United Kingdom
3548,489723,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,288,2009-12-02 10:58:00,0.18,14299.0,United Kingdom
4192,489802,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,3,2009-12-02 12:32:00,0.21,15581.0,United Kingdom
4531,489816,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2009-12-02 13:20:00,0.21,16086.0,United Kingdom
4543,489819,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,96,2009-12-02 13:23:00,0.21,14739.0,United Kingdom
...,...,...,...,...,...,...,...,...
1060258,581171,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2011-12-07 15:02:00,0.29,12615.0,France
1063701,581403,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2011-12-08 13:46:00,0.29,13510.0,United Kingdom
1064307,581419,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,288,2011-12-08 15:03:00,0.21,15484.0,United Kingdom
1065828,581478,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,2011-12-09 08:59:00,0.29,17364.0,United Kingdom
1066009,581492,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,1,2011-12-09 10:03:00,0.63,NaN,United Kingdom

Q4. StockCode in UK
Find out the number of unique StockCode in the United Kingdom according to the given Sales data?

Dataset: https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link

Choose the correct answer from below:

7050

900023

1502

5303

In [15]:
df[df['Country']=='United Kingdom']['StockCode'].nunique()

5303

Q5. Highest Amount Purchase

Mention the Invoice number and Customer ID of the highest amount of purchase based on the given Sales data?

Dataset: https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link

Choose the correct answer from below:

C556445, 15098

581483, 16446

489434, 13085

581587, 12680

In [16]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [25]:
df['total'] = df['Quantity']*df['Price']
df.groupby(['Invoice','Customer ID'])['total'].sum().idxmax()

('581483', np.float64(16446.0))