Q4. Number of customers

Considering the given Sales data, find the number of unique customers who made a purchase on 22nd of June, 2011?

Dataset: https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link

Note: The date should be formatted as YYYY-MM-DD

Choose the correct answer from below:

57

1017

564165659

1280

0

In [32]:
import pandas as pd

file_id = '1UViHcT4lKDsTfc97gBqIvds25uHe4b5e'
df = pd.read_csv(f'https://drive.google.com/uc?id={file_id}')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [33]:
df['date'] = pd.to_datetime(df['InvoiceDate']).dt.strftime('%Y-%m-%d')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,date
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-12-01

In [35]:
df = df[df['date']=='2011-06-22']
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,date
761424,557667,22730,ALARM CLOCK BAKELIKE IVORY,12,2011-06-22 08:30:00,3.75,15606.0,United Kingdom,2011-06-22
761425,557667,85232D,SET/3 DECOUPAGE STACKING TINS,3,2011-06-22 08:30:00,4.95,15606.0,United Kingdom,2011-06-22
761426,557667,22727,ALARM CLOCK BAKELIKE RED,24,2011-06-22 08:30:00,3.75,15606.0,United Kingdom,2011-06-22
761427,557667,23084,RABBIT NIGHT LIGHT,24,2011-06-22 08:30:00,1.79,15606.0,United Kingdom,2011-06-22
761428,557667,22726,ALARM CLOCK BAKELIKE GREEN,24,2011-06-22 08:30:00,3.75,15606.0,United Kingdom,2011-06-22
...,...,...,...,...,...,...,...,...,...
762436,557793,82567,"AIRLINE LOUNGE,METAL SIGN",1,2011-06-22 17:30:00,2.10,14998.0,United Kingdom,2011-06-22
762437,557793,21172,PARTY METAL SIGN,2,2011-06-22 17:30:00,1.45,14998.0,United Kingdom,2011-06-22
762438,557793,22426,ENAMEL WASH BOWL CREAM,1,2011-06-22 17:30:00,3.75,14998.0,United Kingdom,2011-06-22
762439,557793,22429,ENAMEL MEASURING JUG CREAM,1,2011-06-22 17:30:00,4.25,14998.0,United Kingdom,2011-06-22
762440,557793,22425,ENAMEL COLANDER CREAM,1,2011-06-22 17:30:00,4.95,14998.0,United Kingdom,2011-06-22

In [36]:
df['Customer ID'].nunique()

57